### ISSUE TITLE
frontend react 

### ISSUE THREAD

**Issue by BNSBNS** [BNSBNS/ToyProjectAIML#3]
front end should have:

1) login-logout page
2) navbar for to demonstrate the concept 
3) standard simple UI

**Comment by Arnold-Mwangi** [comment]
Yes, the login , logout , navbar are components:
Components help in code separation and assists in easy debugging
here is an example of a react folder structure:
[https://i.stack.imgur.com/741Ng.png](https://i.stack.imgur.com/741Ng.png)

**Comment by lusifer65** [comment]
can you assign to me ?
because i want to work on that

**Comment by Ved-srv** [comment]
I can do that for you, please assign it to me

**Comment by BNSBNS** [comment]
Hi friends, thank you for the interest, I will be doing it on my end instead. Will your interests in mind and keep you posted for future phase ! Much appreciation.
